version: '3.1'
services:
  adminer:
    container_name: mariadb
    restart: always
    image: mariadb
    environment:
      MYSQL_DATABASE: 'database_name'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'user' 
    ports:
      - "3306:3306"
    volumes:
      - "./database-volume:/var/lib/mysql"